version: '3.8'

services:
  anonymization-service:
    build: ./anonymization-service
    ports:
      - "5000:5000"

  comparison-service:
    build: ./comparison-service
    ports:
      - "5001:80"
    depends_on:
      - db

  db:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: default
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./database/scripts:/docker-entrypoint-initdb.d/
    # command: ["-c", "shared_preload_libraries='pg_stat_statements'", "-c", "pg_stat_statements.track=all"]

volumes:
  postgres-data:
