// <auto-generated />
using System;
using FaceComparisonAPI.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace comparison_service.Migrations
{
    [DbContext(typeof(FaceComparisonDbContext))]
    [Migration("20230505015654_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("caf")
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("FaceComparisonAPI.Models.AnonymizedFace", b =>
                {
                    b.Property<Guid>("Identifier")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("identifier");

                    b.Property<double[]>("Embedding")
                        .IsRequired()
                        .HasColumnType("double precision[]")
                        .HasColumnName("embedding");

                    b.HasKey("Identifier");

                    b.ToTable("anonymized_faces", "caf");
                });
#pragma warning restore 612, 618
        }
    }
}
